
spring:
  redis:
#     host: localhost
#     port: 6379
    cluster:
      nodes:
      - 172.17.23.211:30001
      - 172.17.23.211:30002
      - 172.17.23.211:30003
  profiles: local
  cloud:
    gateway:
      routes:
      - id: redirectRoute
        uri: http://172.17.22.126:9081/getname
        predicates:
        - Path=/path2
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@defaultKeyResolver}"
            ct-rate-limiter.replenishRate: 300
            ct-rate-limiter.burstCapacity: 300
#         - name: RequestRateLimiter
#           args:
#             key-resolver: "#{@newResolver}"
#             redis-rate-limiter.replenishRate: 1
#             redis-rate-limiter.burstCapacity: 1      
        - name: Hystrix
          args:
            name: fallbackcmd
#             fallbackUri: forward:/fallback
      - id: HeaderMatching
        uri: http://172.17.22.126:9081/getname
        predicates:
        - Path=/header
        - Header=X-Request-Id, \d+
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@defaultKeyResolver}"
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 10
      - id: HystrixExample
        uri: http://localhost:9081/getname
        predicates:
        - Path=/checkingfallback
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/world
      - id: MethodMatching
        uri: http://localhost:9080/world
        predicates:
        - Path=/post
        - Method=POST
      - id: dummypath
        uri: http://localhost:9080/world
        predicates:
        - Path=/dummy

rate-limit:
  # Specify route specific rate limiting here #
  email:
    paytm:
      ##     the syntax for list is : [replenishRate, BurstRate]
      redirectRoute: [1,1]
      HeaderMatching: [10,10]
      HystrixExample: [2,2]
    "[shubham.bansal@cleartrip.com]":
      redirectRoute: [10,10]
#     192.168.45.116:
#       redirectRoute: [50,50]
    #localhost:
     # redirectRoute: [50,50]
  # In case no rate limiting is defined above, use this #    
  defaultRateLimit:
    localhost: [10,10]
    
    
    
    
refresh:
  configuration:
    url: http://localhost:9080/actuator/refresh
    cron: "0 0 * * * *"

#Hystrix settings
hystrix:
  command:
    fallbackcmd:
     execution:
      isolation:
        strategy: semaphore
        semaphore:
          maxConcurrentRequests: 4
     fallback:
      isolation:
        semaphore:
          maxConcurrentRequests: 10
     circuitBreaker:
      requestVolumeThreshold: 10
